export const GET_VIDEOGAMES = "GET_VIDEOGAMES"
export const GET_DETAIL = "GET_DETAIL"
export const CLEAR_DETAIL = "CLEAR_DETAIL"
export const GET_BY_NAME = "GET_BY_NAME"
export const POST_VIDEOGAME = "POST_VIDEOGAME"
export const GET_GENRES = "GET_GENRES"
export const FILTER = "FILTER"
export const RESET = "RESET"